name: Greeting Java

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  greeting-java-job:
    name: Build and Deploy Greetings
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build with Maven Wrapper
        shell: cmd
        run: F:\tools\maven-3\bin\mvn clean package -DskipTests

      - name: Deploy war file
        run: copy target\*.war F:\tools\tomcat-11\webapps
        